name: CICD

on:
  push:
    branches:
      - master
  workflow_dispatch: # This adds a manual "Run"  button so you can test it easily!

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build Application
        run: mvn clean package